# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=30, verbose_name='商品货号'),
        ),
    ]
